"""Pure backend contract and status types for the overlay client."""

from .contracts import (
    BackendBundle,
    BackendDescriptor,
    BackendFamily,
    BackendInstance,
    CapabilityClassification,
    FallbackReason,
    HelperKind,
    HelperIpcBackend,
    InputPolicyBackend,
    OperatingSystem,
    PlatformProbe,
    PlatformProbeResult,
    PresentationBackend,
    SessionType,
    TargetDiscoveryBackend,
)
from .helper_ipc import (
    HELPER_PROTOCOL_VERSION,
    HelperBoundaryConfig,
    HelperBoundaryError,
    HelperEndpointConfig,
    HelperMessage,
    HelperMessageType,
    HelperTransport,
    parse_helper_message,
    validate_helper_boundary,
)
from .probe import ProbeInputs, ProbeSource, collect_platform_probe
from .selector import BackendSelector
from .status import BackendSelectionStatus, HelperCapabilityState

__all__ = [
    "BackendBundle",
    "BackendSelector",
    "BackendDescriptor",
    "BackendFamily",
    "BackendInstance",
    "BackendSelectionStatus",
    "CapabilityClassification",
    "FallbackReason",
    "HELPER_PROTOCOL_VERSION",
    "HelperBoundaryConfig",
    "HelperBoundaryError",
    "HelperCapabilityState",
    "HelperEndpointConfig",
    "HelperIpcBackend",
    "HelperKind",
    "HelperMessage",
    "HelperMessageType",
    "HelperTransport",
    "InputPolicyBackend",
    "OperatingSystem",
    "PlatformProbe",
    "PlatformProbeResult",
    "PresentationBackend",
    "ProbeInputs",
    "ProbeSource",
    "SessionType",
    "TargetDiscoveryBackend",
    "collect_platform_probe",
    "parse_helper_message",
    "validate_helper_boundary",
]
