"""Pure backend contract and status types for the overlay client."""

from .contracts import (
    BackendBundle,
    BackendCapabilities,
    BackendDescriptor,
    BackendFamily,
    BackendInstance,
    BackendOverrideOption,
    CapabilityClassification,
    FallbackReason,
    HelperKind,
    HelperRuntime,
    HelperProbeAvailability,
    HelperProbeState,
    HelperIpcBackend,
    InputPolicyBackend,
    OperatingSystem,
    PlatformProbe,
    PlatformProbeResult,
    PresentationBackend,
    SessionType,
    TargetDiscoveryBackend,
)
from .helper_ipc import (
    GNOME_SHELL_ALLOWED_EVENTS,
    GNOME_SHELL_HELPER_INTERFACE_NAME,
    GNOME_SHELL_HELPER_OBJECT_PATH,
    GNOME_SHELL_HELPER_SERVICE_NAME,
    GNOME_SHELL_HELPER_SET_OVERLAY_INPUT_PASSTHROUGH_METHOD,
    HELPER_PROTOCOL_VERSION,
    HelperBoundaryConfig,
    HelperBoundaryError,
    HelperEndpointConfig,
    HelperMessage,
    HelperMessageType,
    HelperTransport,
    build_gnome_shell_helper_boundary,
    parse_helper_message,
    validate_helper_boundary,
)
from .gnome_helper_control import GnomeShellHelperControlClient
from .gnome_helper_runtime import GnomeShellHelperIpcBackend, GnomeShellHelperRuntime
from .probe import ProbeInputs, ProbeSource, collect_platform_probe
from .probe_gnome import probe_gnome_shell_helper
from .override_options import (
    backend_override_option,
    backend_override_options_for_status,
    backend_override_requires_restart,
)
from .selector import BackendSelector
from .status import BackendSelectionStatus, HelperCapabilityState

__all__ = [
    "BackendBundle",
    "BackendCapabilities",
    "BackendSelector",
    "BackendDescriptor",
    "BackendFamily",
    "BackendInstance",
    "BackendOverrideOption",
    "BackendSelectionStatus",
    "CapabilityClassification",
    "FallbackReason",
    "GNOME_SHELL_ALLOWED_EVENTS",
    "GNOME_SHELL_HELPER_INTERFACE_NAME",
    "GNOME_SHELL_HELPER_OBJECT_PATH",
    "GNOME_SHELL_HELPER_SERVICE_NAME",
    "GNOME_SHELL_HELPER_SET_OVERLAY_INPUT_PASSTHROUGH_METHOD",
    "GnomeShellHelperControlClient",
    "GnomeShellHelperIpcBackend",
    "GnomeShellHelperRuntime",
    "HELPER_PROTOCOL_VERSION",
    "HelperRuntime",
    "HelperBoundaryConfig",
    "HelperBoundaryError",
    "HelperCapabilityState",
    "HelperEndpointConfig",
    "HelperIpcBackend",
    "HelperKind",
    "HelperProbeAvailability",
    "HelperProbeState",
    "HelperMessage",
    "HelperMessageType",
    "HelperTransport",
    "InputPolicyBackend",
    "OperatingSystem",
    "PlatformProbe",
    "PlatformProbeResult",
    "PresentationBackend",
    "ProbeInputs",
    "ProbeSource",
    "probe_gnome_shell_helper",
    "build_gnome_shell_helper_boundary",
    "backend_override_option",
    "backend_override_options_for_status",
    "backend_override_requires_restart",
    "SessionType",
    "TargetDiscoveryBackend",
    "collect_platform_probe",
    "parse_helper_message",
    "validate_helper_boundary",
]
